// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1xLhXsdm-Kst9A8-yihntDJ_NlEsPZDk',
    appId: '1:974691282710:web:4de2f7a05834d940352a37',
    messagingSenderId: '974691282710',
    projectId: 'dogonomics',
    authDomain: 'dogonomics.firebaseapp.com',
    storageBucket: 'dogonomics.firebasestorage.app',
    measurementId: 'G-YJDBX1TBJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAyWevxKdVTZGw5-BHBG4eYhYCM13f5tU',
    appId: '1:974691282710:android:ff90c6a9d6e4eb72352a37',
    messagingSenderId: '974691282710',
    projectId: 'dogonomics',
    storageBucket: 'dogonomics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt_pU9lqvSmJgGV1OaXC3624pqAx-wgZU',
    appId: '1:974691282710:ios:91724ad1f1eb9641352a37',
    messagingSenderId: '974691282710',
    projectId: 'dogonomics',
    storageBucket: 'dogonomics.firebasestorage.app',
    iosBundleId: 'com.example.dogonomicsFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt_pU9lqvSmJgGV1OaXC3624pqAx-wgZU',
    appId: '1:974691282710:ios:91724ad1f1eb9641352a37',
    messagingSenderId: '974691282710',
    projectId: 'dogonomics',
    storageBucket: 'dogonomics.firebasestorage.app',
    iosBundleId: 'com.example.dogonomicsFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1xLhXsdm-Kst9A8-yihntDJ_NlEsPZDk',
    appId: '1:974691282710:web:f521dda6ed1de3a9352a37',
    messagingSenderId: '974691282710',
    projectId: 'dogonomics',
    authDomain: 'dogonomics.firebaseapp.com',
    storageBucket: 'dogonomics.firebasestorage.app',
    measurementId: 'G-3QJKTR3N74',
  );
}
